### PR TITLE
Updated the abc api addresses

### PR DESCRIPTION
**Pull request by flareofghast**

### CODE REVIEW

**Comment by robotiv** [comment]
I tried these and am still getting errors on the abc website, nothing will play.

**Comment by flareofghast** [comment]
Works fine for me, you remembered to change the ip and username and password, restart the server after replacing the file/entries. Got all the commas in the right place?

**Comment by flareofghast** [comment]
and updated both the dnsmasq and haproxy files

**Comment by flareofghast** [comment]
Ohhhh k, I just realised that the program I used to change this file at one point inserted incorrect " and messed everything up. This should hopefully fix the issue

**Pull request merged**
